@startuml
'https://plantuml.com/sequence-diagram



actor       User                                as user
boundary    "sp: Student_page"                  as sp
control     "slc: Student_list_controller"      as slc
boundary    "Edit_student_name_fabric"          as esnf
boundary    "asw: Edit_student_name_window"     as asw
boundary    "asc: Edit_student_controller"      as asc
entity      "sl: Student_list"                  as sl
entity      "dlss: Data_list_student_short"     as dlss

user -> sp : click "edit" button
sp -> slc : edit_student
slc -> esnf : create
esnf -> asc : <<new>>
asc -> asc : set_textfields
esnf <-- asc :
user <-- esnf
user -> asw : click <<Ok>>
asw -> asc : accept_student
asc -> asc :check valid
asc -> asc :get_student_hash
asc -> sl : replace_student_by_id
asc <-- sl
asw <- asc : close
slc <-- asw
slc -> slc :refresh_data
slc -> sl : get_k_n_student_short
sl -> dlss : list=
dlss -> dlss : notify
sp <- dlss : set_table_params
sp --> dlss
sp <- dlss : set_table_data
user <-- sp
@enduml